#!/usr/bin/env bash
set -e

curl -sL https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh | bash

export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"

gobrew use latest

# Formatter
go install github.com/segmentio/golines@latest
# golines will use goimports as a base formatter if it is installed on the system
go install golang.org/x/tools/cmd/goimports@latest

# Debugger
go install github.com/go-delve/delve/cmd/dlv@latest

# binary will be $(go env GOPATH)/bin/golangci-lint
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
