#!/usr/bin/env bash
set -e

curl -sL https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh | bash

export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"

gobrew use latest
