#!/usr/bin/env bash

git clone -b v0.10.1 https://github.com/neovim/neovim.git $HOME/neovim
sudo apt-get install ninja-build gettext cmake unzip curl build-essential lua5.1 liblua5.1-0-dev

cd $HOME/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
